### ISSUE TITLE
NotificationChanged crash on MSIX installations to new computers

### ISSUE THREAD

**Issue by forderud** [forderud/ToastNotifier#1]
The https://github.com/forderud/ToastNotifier/blob/main/ToastNotifier/MainWindow.xaml.cs#L50 line is triggering a `System.Runtime.InteropServices.COMException (0x800706BE): The remote procedure call failed. (0x800706BE)` when starting the app on a clean computer after a MSIX installation. The problem is not reproducible when starting the `ToastNotifier` project from Visual Studio or when installing on a dev computer.
![image](https://user-images.githubusercontent.com/2671400/167594754-c58a2846-cb21-4fcf-b9a5-02badc486b73.png)
![image](https://user-images.githubusercontent.com/2671400/170061220-bd2750e6-df74-4fbb-a794-2f08770a7171.png)

```
NotificationChanged error
---------------------------
System.Runtime.InteropServices.COMException (0x800706BE): The remote procedure call failed. (0x800706BE)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at WinRT.EventSource`1.Subscribe(TDelegate del)
   at Windows.UI.Notifications.Management.UserNotificationListener.add_NotificationChanged(TypedEventHandler`2 value)
   at ToastNotifierWpf.MainWindow.InitalizeListener()
```

This is not the same error as if running the executable directly without AppContainer sandboxing. You'll then instead get a "Element not found" error:
![image](https://user-images.githubusercontent.com/2671400/167610023-f354cb9e-5ecc-4617-bb09-f4860305b3fb.png)

This is kind of strange since `m_listener.RequestAccessAsync()` returned `UserNotificationListenerAccessStatus.Allowed` a few lines above.

Things to test:
* Run as admin: Didn't help
* Add Add Microsoft.Windows.SDK.BuildTools dependency back: Didn't help
* internetClient capability: Didn't help
* internetServer capability: TBD

**Comment by forderud** [comment]
Problem solved by switching to "UserNotificationChanged"-based background notification in ToastNotifierUWP as documented in https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/notification-listener#background-task-for-notification-addeddismissed

Foreground notification handling as documented in https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/notification-listener#foreground-event-for-notification-addeddismissed appear buggy.
